[package]
name = "tap-ldk-core"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
name = "tap_ldk_core"
path = "src/lib.rs"

[dependencies]
bech32 = "0.9"
ldk-node = { git = "https://github.com/OpenAgentsInc/ldk-node.git", rev = "ce6319df7220aa39cd561fee50ea7115a0b7dd73" }
lightning = { git = "https://github.com/OpenAgentsInc/rust-lightning", rev = "5cee3fd83db4822eb7b05a5779aa4149d228238f", package = "lightning", features = ["simple_taproot_musig2"] }
ripemd = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"

[lints]
workspace = true

[dev-dependencies]
