[package]
name = "tap-ldk-core"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
name = "tap_ldk_core"
path = "src/lib.rs"

[dependencies]
bech32 = "0.9"
ldk-node = { git = "https://github.com/OpenAgentsInc/ldk-node.git", rev = "5b4fdf7770426ba18ed1aece050b3d0da76d2968" }
lightning = { git = "https://github.com/OpenAgentsInc/rust-lightning", rev = "4761230b3d8a2732d379087a5510456a13b86c29", package = "lightning", features = ["simple_taproot_musig2"] }
ripemd = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"

[lints]
workspace = true

[dev-dependencies]
