[package]
name = "tap-ldk-core"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
name = "tap_ldk_core"
path = "src/lib.rs"

[dependencies]
bech32 = "0.9"
ldk-node = { git = "https://github.com/OpenAgentsInc/ldk-node.git", rev = "fefcc5747b84145b1c85a76fde13848b445ffc3a" }
lightning = { git = "https://github.com/OpenAgentsInc/rust-lightning", rev = "acce215e1ca284fa45f1c13e13760de459d410d4", package = "lightning", features = ["simple_taproot_musig2"] }
ripemd = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"

[lints]
workspace = true

[dev-dependencies]
